### ISSUE TITLE
Possible deprecated access

### ISSUE THREAD

**Issue by johnbester** [xenserver/xenadmin#1290] opened 2016-11-15 08:33 UTC
I am trying to build XenAdmin for Linux and the build process breaks on an issue that has been around for some time. Not being a C# expert (my expertise lies in Java) I did think at first this was a Mono implementation issue and logged it as such, but it might be that my initial analysis was incorrect. The following build error prevents the project to be build by Mono:

	Target GenerateResources:
		Tool /usr/lib/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "Dialogs/ConfirmVMDeleteDialog.resx,obj/Debug/XenAdmin.Dialogs.ConfirmVMDeleteDialog.resources" 
/usr/lib/mono/4.5/Microsoft.Common.targets: error : Tool exited with code: 1. Output: Error: Exception has been thrown by the target of an invocation.
Inner exception: Member 'ListViewItemCount' was not found.

	Task "GenerateResource" execution -- FAILED
	Done building target "GenerateResources" in project "/data/projects/build/xenadmin/XenAdmin/XenAdmin.csproj".-- FAILED

I have commented out references to ConfirmVMDeleteDialog in DeleteVMCommand.cs as well as in XenAdmin.csproj and then the build completes successfully. It might be that access to ListViewItem count should be replaced by a different property / function. My reason for saying this is if it was a bug in Mono, the Xamarin team should have fixed the bug by now (since I logged it more than 6 months ago if I remember correctly).

If I am wrong, there may be a different way to resolve the issue - is there is a way to use compiler flags to replace access to ListViewItemCount with some other property or function that does the same in Mono as a temporary solution?

**Comment by stephen-turner** [comment] 2016-11-15 12:27
I'm confused by this, because there is no instance of "ListViewItemCount" in the source. That would suggest it's something internal to Mono, wouldn't it?

**Comment by johnbester** [comment] 2016-11-17 05:00
Hi Stephen,
    
    Thanks for your quick response. Yes - after I posted the message I
    went back and read through all the messages I posted about this and
    found that I
    came the same conclusion 6 months ago. I did log into the message I
    posted on Xamarin / Mono web site. There were bug reports for that
    particular
    component that was still open and no one ever commented on my bug
    report. I also looked at a different component and found that it
    seems to be
    actively tracked, so I changed my Mono bug report. My appologies, I
    should have done my research before I posted the bug.
    
    On another note - I am very keen on this project compiling
    successfully on Mono. It seems to be so close now and apart from the
    cyclic dependency
    (which I did report as well), this Mono bug is the only real show
    stopper. The only other problem is that the only exe that is
    generated is for the health
    check, but I am sure this is something small that can easily be
    sorted out once the project compiles in Mono without commenting out
    some code.
    
    Regards
    John
    
    On 15/11/2016 14:27, Stephen Turner wrote:
    
      I'm confused by this, because there is no instance of
        "ListViewItemCount" in the source. That would suggest it's
        something internal to Mono, wouldn't it?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xenserver/xenadmin","title":"xenserver/xenadmin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xenserver/xenadmin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stephen-turner in #1290: I'm confused by this, because there is no instance of \"ListViewItemCount\" in the source. That would suggest it's something internal to Mono, wouldn't it?"}],"action":{"name":"View Issue","url":"https://github.com/xenserver/xenadmin/issues/1290#issuecomment-260628200"}}}

**Comment by stephen-turner** [comment] 2016-11-17 09:35
I would love to see this working too. Even if Citrix doesn't officially publish or support it, it would be people another option.

**Comment by stephen-turner** [comment] 2016-12-21 09:35
I think this is a dupe of #3.

**Closed by stephen-turner** 2016-12-21 09:35 UTC
