### ISSUE TITLE
XenCenter on Linux

### ISSUE THREAD

**Issue by Outstep** [xenserver/xenadmin#2455] opened 2019-06-18 23:25 UTC
Hello,

Sorry to ask this question here as I did not know where else to ask it, but as XenCenter is C# then I am wondering if it would also run on Linux under Mono perhaps?

Thanks

**Comment by kc284** [comment] 2019-06-24 10:25
Please see https://github.com/xenserver/xenadmin/issues/3.
Closing this as duplicate of the latter.

**Closed by kc284** 2019-06-24 10:25 UTC
