### ISSUE TITLE
Can't move VDISK within Local SR

### ISSUE THREAD

**Issue by Petahh** [xenserver/xenadmin#2454] opened 2019-06-18 07:29 UTC
Dear developers,
Relatively straight forward problem. I can't move VDISK between Local SRs.
No idea if this was intention to disable in higher versions or a bug.
This behavior is not observed in Version 7.6.1.
I can observe this in version 7.6.3 upwards till latest release.

![Screenshot 2019-06-18 at 09 24 31](https://user-images.githubusercontent.com/7292374/59661548-58fe3280-91ab-11e9-98c9-54c293186b51.jpg)

Thank you very much for your support and for making this amazing project possible!

**Comment by kc284** [comment] 2019-06-24 14:37
First of all, you are using https://github.com/xcp-ng/xenadmin which is an independent fork of the current repo and have different release and versioning cycles, so issues with that client should be first reported to their issue page and only escalated here if it is proven they are upstream problems.

Beyond this, if your VM has no home server assigned, by design you can't move the vdi to local sr. As a workaround, do "Move VM" instead which will also allow you to set a home server on the VM.

**Comment by borzel** [comment] 2019-06-25 00:09
@kc284 I think you did not understand @Petahh s issue correctly. He wants to move a VDI from a local SR to another local SR. One Server, no "Pool", so the home server thing should not matter, because there is only one host.

**Comment by kc284** [comment] 2019-06-26 10:03
@borzel @Petahh do you know which Citrix Hypervisor / XenServer versions correspond to the XCP-ng versions you are referencing above?

**Comment by stormi** [comment] 2019-06-26 10:15
Hi Konstantina!

The versions referenced above are XCP-ng Center versions (close fork of XenCenter). XCP-ng itself keeps the same versioning as Citrix Hypervisor. From what I understand, this is mostly related to a change in the code of XenCenter here, since XenOrchestra is able to move the VDISK. I guess @borzel and @Petahh will be able to specify which versions of XCP-ng they are using if that's relevant. Probably 7.6.0, 8.0.0 or both, which will translate to the exact same versions of XenServer / Citrix Hypervisor.

**Comment by Petahh** [comment] 2019-06-26 14:26
xen-hypervisor 4.7.6

**Comment by stormi** [comment] 2019-06-26 14:29
> xen-hypervisor 4.7.6

Ok, so either XenServer 7.6 or XCP-ng 7.6.

**Comment by Petahh** [comment] 2019-06-26 14:31
XCP-ng sorry forgot to mention.

**Comment by kc284** [comment] 2019-06-28 10:50
Ok, at the moment the move between local SRs is disallowed even if the VM has a home server and the target SR can be seen from the host, which I suppose is unexpected. I can't identify a regression though, and the code preventing this is fairly old. In any case, I'll re-open this issue for us to look at.

**Comment by borzel** [comment] 2019-06-28 21:10
I also saw the old code, this is why I asked back to you with increased force :-)

**Comment by kc284** [comment] 2019-07-22 16:44
Hello, we have just merged #2465, hence I'll close this issue. Please let us know if you still face problems.

**Closed by kc284** 2019-07-22 16:44 UTC
